### ISSUE TITLE
vocab / doc quest 

### ISSUE THREAD

**Issue by tcql** [mapbox/probematch#6]
In light of #5, and general confusion around what probematch does and returns, terminology and descriptions should be extremely consistent. 
- [x] Document outputs and terminology - [draft](https://gist.github.com/tcql/81b7f8ba100d6db910ed2d57a982ce32)
- Consistify terms in docs AND code:
  - [x] `line` -> `road`, in the context of results returned from matching
  - [x] `line` -> `trace` in the context of a trace being matched to the road network, as in `matchLine` ( -> matchTrace)
  - [x] `point` -> `probe` 
  - [x] `featurecollection` -> `road network` anywhere that this makes sense

**Comment by aaronlidman** [comment]
This happened in #7
