### ISSUE TITLE
compareBearing base ~= 0˚ incomplete

### ISSUE THREAD

**Issue by lily-chai** [mapbox/probematch#9]
Say for example base = 3˚, range = 8˚. 
[L199](https://github.com/mapbox/probematch/blob/master/probematch.js#L199) checks for a bearing within -5˚ ~ 11˚. Bearings in the range of 355˚ to 359˚ will fail this check. 

cc @tcql

**Comment by danpat** [comment]
For a working implementation of this logic, see:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/bearing.hpp#L65

and corresponding tests:

https://github.com/Project-OSRM/osrm-backend/blob/master/unit_tests/util/bearing.cpp#L14
